/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocalRouteImport } from './routes/local'
import { Route as SyncedRouteRouteImport } from './routes/_synced/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SyncedServerRouteImport } from './routes/_synced/server'
import { Route as SyncedClientRouteImport } from './routes/_synced/client'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const LocalRoute = LocalRouteImport.update({
  id: '/local',
  path: '/local',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncedRouteRoute = SyncedRouteRouteImport.update({
  id: '/_synced',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SyncedServerRoute = SyncedServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => SyncedRouteRoute,
} as any)
const SyncedClientRoute = SyncedClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => SyncedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/local': typeof LocalRoute
  '/client': typeof SyncedClientRoute
  '/server': typeof SyncedServerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/local': typeof LocalRoute
  '/client': typeof SyncedClientRoute
  '/server': typeof SyncedServerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_synced': typeof SyncedRouteRouteWithChildren
  '/local': typeof LocalRoute
  '/_synced/client': typeof SyncedClientRoute
  '/_synced/server': typeof SyncedServerRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/local' | '/client' | '/server' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/local' | '/client' | '/server' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_synced'
    | '/local'
    | '/_synced/client'
    | '/_synced/server'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SyncedRouteRoute: typeof SyncedRouteRouteWithChildren
  LocalRoute: typeof LocalRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/local': {
      id: '/local'
      path: '/local'
      fullPath: '/local'
      preLoaderRoute: typeof LocalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_synced': {
      id: '/_synced'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SyncedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_synced/server': {
      id: '/_synced/server'
      path: '/server'
      fullPath: '/server'
      preLoaderRoute: typeof SyncedServerRouteImport
      parentRoute: typeof SyncedRouteRoute
    }
    '/_synced/client': {
      id: '/_synced/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof SyncedClientRouteImport
      parentRoute: typeof SyncedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SyncedRouteRouteChildren {
  SyncedClientRoute: typeof SyncedClientRoute
  SyncedServerRoute: typeof SyncedServerRoute
}

const SyncedRouteRouteChildren: SyncedRouteRouteChildren = {
  SyncedClientRoute: SyncedClientRoute,
  SyncedServerRoute: SyncedServerRoute,
}

const SyncedRouteRouteWithChildren = SyncedRouteRoute._addFileChildren(
  SyncedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SyncedRouteRoute: SyncedRouteRouteWithChildren,
  LocalRoute: LocalRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
